// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package funds_mock

import (
	"ca/internal/types/catalog"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newFundsRepositoryMock creates a new instance of fundsRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newFundsRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *fundsRepositoryMock {
	mock := &fundsRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// fundsRepositoryMock is an autogenerated mock type for the fundsRepository type
type fundsRepositoryMock struct {
	mock.Mock
}

type fundsRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *fundsRepositoryMock) EXPECT() *fundsRepositoryMock_Expecter {
	return &fundsRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type fundsRepositoryMock
func (_mock *fundsRepositoryMock) GetAll(ctx context.Context, page uint64) ([]catalog.Fund, error) {
	ret := _mock.Called(ctx, page)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []catalog.Fund
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) ([]catalog.Fund, error)); ok {
		return returnFunc(ctx, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) []catalog.Fund); ok {
		r0 = returnFunc(ctx, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]catalog.Fund)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// fundsRepositoryMock_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type fundsRepositoryMock_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint64
func (_e *fundsRepositoryMock_Expecter) GetAll(ctx interface{}, page interface{}) *fundsRepositoryMock_GetAll_Call {
	return &fundsRepositoryMock_GetAll_Call{Call: _e.mock.On("GetAll", ctx, page)}
}

func (_c *fundsRepositoryMock_GetAll_Call) Run(run func(ctx context.Context, page uint64)) *fundsRepositoryMock_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *fundsRepositoryMock_GetAll_Call) Return(funds []catalog.Fund, err error) *fundsRepositoryMock_GetAll_Call {
	_c.Call.Return(funds, err)
	return _c
}

func (_c *fundsRepositoryMock_GetAll_Call) RunAndReturn(run func(ctx context.Context, page uint64) ([]catalog.Fund, error)) *fundsRepositoryMock_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
